### ISSUE TITLE
CVE for package used in 0.3.1

### ISSUE THREAD

**Issue by Danghor** [tudalgo/algoutils#25]
The current version 0.3.1 shows a vulnerability warning in IntelliJ. Apparently, a package is used, for which a CVE exists.

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/7728268/196641536-abec8895-ea44-4a06-a879-3e404ec75689.png">

**Comment by alexstaeding** [comment]
Waiting on https://github.com/INRIA/spoon/pull/4967

**Comment by alexstaeding** [comment]
Fixed by #26
