### ISSUE TITLE
Get all imports of a class/method

### ISSUE THREAD

**Issue by zentox** [tudalgo/algoutils#58]
Add a method in [TypeLink](https://github.com/tudalgo/algoutils/blob/master/tutor/src/main/java/org/tudalgo/algoutils/tutor/general/reflections/TypeLink.java) and [MethodLink](https://github.com/tudalgo/algoutils/blob/master/tutor/src/main/java/org/tudalgo/algoutils/tutor/general/reflections/MethodLink.java) showing all used classes.

**Comment by Rdeisenroth** [comment]
Closing as not relevant for this semester. Reopen if we have a valid usecase.
