### ISSUE TITLE
NPE when `Assertions2#callObject` Callable parameter throws an exception

### ISSUE THREAD

**Issue by tth05** [tudalgo/algoutils#92]
Example code:
```java
var scanRobots = Assertions2.callObject(
	controlCenter::initScanRobots,
    context,
    r -> "The method `initScanRobots` threw an exception."
);
```

If the `initScanRobots` method throws an exception, an NPE is thrown [here](https://github.com/tudalgo/algoutils/blob/master/tutor/src/main/java/org/tudalgo/algoutils/tutor/general/assertions/basic/BasicResult.java#L61) because the `actual` field is `null`. 

Instead, I would expect this to throw an `AssertionFailedError` with the exception thrown by `initScanRobots` as a cause, just like `Assertions2#call`.

A possible fix might be to just add `Nothing.nothing()` as the actual value to the builder [here](https://github.com/tudalgo/algoutils/blob/master/tutor/src/main/java/org/tudalgo/algoutils/tutor/general/assertions/basic/BasicTestOfObject.java#L34).

**Comment by Rdeisenroth** [comment]
Reopening due to not being fixed apparently

**Comment by Rdeisenroth** [comment]
Actually, https://github.com/tudalgo/algoutils/commit/466c71054caea236f348461698c611a133423087 fixed it and i didn't update the dependency
